# Generated by Django 4.1.7 on 2023-04-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Event_Name', models.CharField(max_length=100)),
                ('Contact_Number', models.IntegerField()),
                ('Email_ID', models.EmailField(max_length=254)),
            ],
        ),
    ]
