# Generated by Django 4.1.7 on 2023-04-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MysqlApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registerform',
            table='regdata',
        ),
    ]
